[build]
  command = "npm run build"
  publish = "dist"

# For Chinese article dynamic routes
[[redirects]]
  from = "/zh-tw/articles/*"
  to = "/zh-tw/articles/[slug].html"
  status = 200
  force = true

# For Chinese tag dynamic routes
[[redirects]]
  from = "/zh-tw/tags/*"
  to = "/zh-tw/tags/[tag].html"  
  status = 200
  force = true

# redirect missing pages to the 404 page
[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/zh-tw/*"
  to = "/zh-tw/404.html"
  status = 404

# Handle root 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
