[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

[[redirects]]  
  from = "/"
  to = "/zh-tw/"
  status = 302
  condition = "Language=zh"

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/zh-tw/*"
  to = "/zh-tw/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
