[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["zh", "zh-tw"]}

[[redirects]]
  from = "/zh-tw/*"
  to = "/zh-tw/index.html"
  status = 200
  force = false

# redirect missing pages to the 404 page
[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/zh-tw/*"
  to = "/zh-tw/404.html"
  status = 404

# Handle root 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
