[build]
  command = "npm run build"
  publish = "dist"

# Redirect Chinese users to Chinese version
[[redirects]]
  from = "/"
  to = "/zh-tw/"
  status = 302
  condition = "Language=zh"

# Redirect old /en/* URLs to root (for backwards compatibility)
[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 301

# 404 handling
[[redirects]]
  from = "/zh-tw/*"
  to = "/zh-tw/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
